### ISSUE TITLE
Error handling in quassel_setpass

### ISSUE THREAD

**Issue by aykevl** [karpenoktem/kninfra#403]
Het systeem lockt bij het instellen van een wachtwoord, met deze error:

```
ERROR:threadPool:Uncaught exception
Traceback (most recent call last):
  File "/home/infra/py/mirte/threadPool.py", line 31, in run
    ret = job()
  File "/home/infra/py/mirte/threadPool.py", line 130, in _entry
    function(*args, **kwargs)
  File "/home/infra/repo/kn/utils/whim.py", line 186, in __handle
    ret = self.handle(msg)
  File "/home/infra/repo/kn/utils/daan/__init__.py", line 66, in handle
    quassel_setpass(self, d['user'], d['pass'])
  File "/home/infra/repo/kn/utils/daan/quassel.py", line 16, in quassel_setpass
    (hashed_pw, user))
OperationalError: database is locked
```

**Comment by bwesterb** [comment]
Pak ik op nu.
