### ISSUE TITLE
Vagrant, hoe dan?

### ISSUE THREAD

**Issue by JVerbeek** [karpenoktem/kninfra#522]
Elke keer als ik Vagrant op probeer te starten breken er dingen:
Dit gaat er fout, gevolgd door Vagrant die moeilijk doet:
```
Passed invalid arguments: 'home' is an invalid keyword argument for 'group.present'.

Usage:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 218, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1087, in highstate
    orchestration_jid=orchestration_jid)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 4088, in call_highstate
    return self.state.call_high(high, orchestration_jid)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2909, in call_high
    ret = self.call_chunks(chunks)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2271, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2716, in call_chunk
    running[tag] = self.call(low, chunks, running)
  File "/usr/lib/python2.7/dist-packages/salt/utils/decorators/state.py", line 30, in _func
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1911, in call
    expected_extra_kws=STATE_INTERNAL_KEYWORDS
  File "/usr/lib/python2.7/dist-packages/salt/utils/args.py", line 511, in format_call
    raise SaltInvocationError(msg)
SaltInvocationError: 'home' is an invalid keyword argument for 'group.present'

The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
Ik kan verder niet veel vinden over deze error, noch over de keywords.
Mijn vraag is hoe je dan wel het systeem moet runnen, als niet zo.
Ik weet niet of het relevant is, maar ik run Manjaro Linux en gebruik VirtualBox icm Vagrant.

**Comment by bwesterb** [comment]
"salt" is het systeem dat gebruikt wordt om de servers in te richten (zie de README) en de bestanden daarvoor staan onder de `salt` map.  Laten we zoeken naar `group.present`:

```
$ git grep 'group.present' 
salt/states/phassa/kn.sls:    group.present
salt/states/phassa/kn.sls:    group.present
salt/states/phassa/moniek.sls:    group.present:
salt/states/sankhara/interinfra.sls:    group.present:
salt/states/sankhara/kninfra.sls:    group.present:
salt/states/sankhara/kninfra.sls:    group.present:
```

Als je die bestanden bekijkt zie dat alleen in `moniek.sls`  ook een `home` voorkomt onder `group.present`:

```
[...]
kn-boekenlezers:
    group.present:
        - home: /groups/boekenlezers
[...]
```

Deze regel zorgt ervoor dat er een groep `kn-boekenlezers` aangemaakt wordt.  Wat is de `home` van een groep? Als we op de website van Salt zoeken naar `group.present` [vinden we in de documentatie dat er geen `home` parameter is](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.group.html), dus de foutmelding is redelijk.   Een groep heeft ook geen homemap.  Misschien dat toen dit geschreven is, diegene dacht aan een gebruiker i.p.v. een groep. Wat me verbaast is dat dit vroeger wel heeft gewerkt.  Misschien dat een oudere versie van Salt de parameter negeerde i.p.v. een foutmelding te geven.

Ik heb net mijn `kninfra` git clone afgestoft en verse `vagrant up` gedaan en loop inderdaad tegen dezelfde fout aan.  Ik heb de `- home` instructie weggehaald en dat zou dat moeten oplossen. Merk dat dit om de provisioning van de phassa VM gaat.  Om die verder te laten gaan waar het gecrasht was log ik in op phassa en draai:

```
$ vagrant ssh phassa
Linux vagrant-phassa 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64
     ___   _____   __  __ __                    _  __     __   __   
    / _ | / __/ | / / / //_/__ ________  ___   / |/ /__  / /__/ /____ __ _ 
   / __ |_\ \ | |/ / / ,< / _ `/ __/ _ \/ -_) /    / _ \/  '_/ __/ -_)  ' \
  /_/ |_/___/ |___/ /_/|_|\_,_/_/ / .__/\__/ /_/|_/\___/_/\_\\__/\__/_/_/_/
                 vagrant-phassa  /_/        leden loginserver

You have mail.
vagrant@vagrant-phassa:~$ sudo salt-call state.highstate
(...)
Summary for local
-------------
Succeeded: 82 (changed=33)
Failed:     0
-------------
Total states run:     82
Total run time:   13.805 s
```

Ok, dus phassa is nu goed ingesteld.

sankhara is nog helemaal niet gemaakt, omdat vagrant eerst phassa maakt en er mee stopt als het een probleem tegenkomt.  Dus ik log uit van phassa (die nog in de achtergrond blijft draaien) en draai `vagrant up` opnieuw:

```
$ vagrant up
[...]
--------------
Succeeded: 141 (changed=133)
Failed:      2
--------------
Total states run:     143
Total run time:  1005.141 s
```

Twee fouten.  Dat zijn:

```
          ID: wiki mysql grant 2
    Function: mysql_grants.present
      Result: False
     Comment: Failed to execute: "GRANT select ON wiki.user TO giedo@localhost" (MySQL Error 1133: Can't find any matching row in the user table)
     Started: 18:48:42.415623
    Duration: 9.186 ms
     Changes:   
----------
          ID: wiki mysql grant 3
    Function: mysql_grants.present
      Result: False
     Comment: Failed to execute: "GRANT select ON wiki.user_groups TO giedo@localhost" (MySQL Error 1133: Can't find any matching row in the user table)
     Started: 18:48:42.425258
    Duration: 9.373 ms
     Changes:   
----------
```

Met weer een `git grep` vinden we dat dat uit `salt/states/sankhara/wiki.sls` komt:

```
[...]
wiki mysql grant 2:                                                              
    mysql_grants.present:                                                        
        - grant: select                                                          
        - database: wiki.user                                                    
        - user: giedo                                                            
wiki mysql grant 3:                                                              
    mysql_grants.present:                                                        
        - grant: select                                                          
        - database: wiki.user_groups                                             
        - user: giedo  
[...]
```

Zo te zien is de `giedo` MySQL gebruiker nog niet gemaakt.  Dat lijkt te kloppen, want die wordt gedefinieerd in `kninfra.sls` die volgens `init.sls` pas geladen wordt na `wiki.sls`.  Dus ik heb de instructie om de `giedo` mysql gebruiker te maken verplaatst naar `mysqld.sls` en dat werkt.

**Comment by JVerbeek** [comment]
Top, bedankt.
